<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>yier.bubu.redis</groupId>
        <artifactId>yierdis-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>yierdis-server-runtime</artifactId>
    <description>Embedded runtime assembly and lifecycle for Yierdis.</description>

    <dependencies>
        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-db-memory</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-memory-ffm</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-server-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-command-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-command-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-command-builtin</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources-filtered</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
