<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>yier.bubu.redis</groupId>
        <artifactId>yierdis-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>yierdis-core</artifactId>
    <packaging>jar</packaging>

    <name>yierdis-core</name>
    <description>Core database, data structures and command processor logic for Yierdis.</description>

    <dependencies>
        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-protocol</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-offheap-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-offheap-unsafe</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-offheap-netty</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
