<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>yier.bubu.redis</groupId>
        <artifactId>yierdis-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>yierdis-server</artifactId>
    <packaging>jar</packaging>

    <name>yierdis-server</name>
    <description>A simplified Yierdis server (Custom Protocol v1) built with Netty.</description>

    <dependencies>
        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-core-contract</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-core-command</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-protocol-netty</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-bytes-netty</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-core-runtime</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-executor-core</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-args</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-memory-api</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-memory-netty</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-memory-unsafe</artifactId>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>

        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${shade.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>yier.bubu.redis.YierdisServer</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>foreign-memory</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>yier.bubu.redis</groupId>
                    <artifactId>yierdis-memory-foreign</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
