<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>yier.bubu.redis</groupId>
        <artifactId>yierdis-core</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>yierdis-core-command</artifactId>
    <packaging>jar</packaging>

    <name>yierdis-core-command</name>
    <description>Command layer implementation for Yierdis core.</description>

    <dependencies>
        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-execution-api</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-core-api</artifactId>
        </dependency>

        <dependency>
            <groupId>yier.bubu.redis</groupId>
            <artifactId>yierdis-memory-api</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>ban-core-db</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <excludes>
                                        <exclude>yier.bubu.redis:yierdis-core-db</exclude>
                                        <exclude>yier.bubu.redis:yierdis-protocol-model</exclude>
                                    </excludes>
                                    <searchTransitive>true</searchTransitive>
                                </bannedDependencies>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
