package yier.bubu.redis.storage.api;

/**
 * A best-effort memory budget breakdown for explaining maxmemory / eviction behavior.
 * <p>
 * This is an <b>estimate</b> designed to be stable and explainable, not a precise JVM heap measurement.
 */
public record YierdisMemoryStats(
        long maxmemoryBytes,
        long usedBytesForMaxmemory,
        long heapDataBytesEstimate,
        long offHeapUsedBytes,
        long reservedBytes,
        long effectiveUsedBytesForMaxmemory,
        boolean offHeapIncludedInMaxmemory,
        boolean keysStoredOffHeap,
        int keyCount,
        int expireCount,
        boolean keyspaceRehashing,
        int keyspaceTable0Capacity,
        int keyspaceTable1Capacity,
        long keyspaceTableOverheadBytesEstimate,
        boolean expireRehashing,
        int expireTable0Capacity,
        int expireTable1Capacity,
        long expireTableOverheadBytesEstimate,
        long expireValueObjectsBytesEstimate,
        long totalEstimatedBytes,
        long nativeDefragLastScannedObjects,
        long nativeDefragLastMovedObjects,
        long nativeDefragLastMovedBytes,
        long nativeDefragLastSkippedPinnedObjects,
        long nativeDefragLastSkippedBudgetObjects,
        long nativeDefragLastFailedMoves,
        long nativeDefragMovedBytes,
        long nativeDefragSkippedPinnedObjects,
        long nativeDefragQuarantinedObjects,
        long nativeDefragQuarantineBytes,
        long nativeStaleHandleDetections,
        long nativeDefragReclaimedPages,
        long nativeMetadataCommittedBytes
) {
    public YierdisMemoryStats(
            long maxmemoryBytes,
            long usedBytesForMaxmemory,
            long heapDataBytesEstimate,
            long offHeapUsedBytes,
            long reservedBytes,
            long effectiveUsedBytesForMaxmemory,
            boolean offHeapIncludedInMaxmemory,
            boolean keysStoredOffHeap,
            int keyCount,
            int expireCount,
            boolean keyspaceRehashing,
            int keyspaceTable0Capacity,
            int keyspaceTable1Capacity,
            long keyspaceTableOverheadBytesEstimate,
            boolean expireRehashing,
            int expireTable0Capacity,
            int expireTable1Capacity,
            long expireTableOverheadBytesEstimate,
            long expireValueObjectsBytesEstimate,
            long totalEstimatedBytes,
            long nativeDefragLastScannedObjects,
            long nativeDefragLastMovedObjects,
            long nativeDefragLastMovedBytes,
            long nativeDefragLastSkippedPinnedObjects,
            long nativeDefragLastSkippedBudgetObjects,
            long nativeDefragLastFailedMoves,
            long nativeDefragMovedBytes,
            long nativeDefragSkippedPinnedObjects,
            long nativeDefragQuarantinedObjects,
            long nativeDefragQuarantineBytes,
            long nativeStaleHandleDetections,
            long nativeDefragReclaimedPages
    ) {
        this(
                maxmemoryBytes,
                usedBytesForMaxmemory,
                heapDataBytesEstimate,
                offHeapUsedBytes,
                reservedBytes,
                effectiveUsedBytesForMaxmemory,
                offHeapIncludedInMaxmemory,
                keysStoredOffHeap,
                keyCount,
                expireCount,
                keyspaceRehashing,
                keyspaceTable0Capacity,
                keyspaceTable1Capacity,
                keyspaceTableOverheadBytesEstimate,
                expireRehashing,
                expireTable0Capacity,
                expireTable1Capacity,
                expireTableOverheadBytesEstimate,
                expireValueObjectsBytesEstimate,
                totalEstimatedBytes,
                nativeDefragLastScannedObjects,
                nativeDefragLastMovedObjects,
                nativeDefragLastMovedBytes,
                nativeDefragLastSkippedPinnedObjects,
                nativeDefragLastSkippedBudgetObjects,
                nativeDefragLastFailedMoves,
                nativeDefragMovedBytes,
                nativeDefragSkippedPinnedObjects,
                nativeDefragQuarantinedObjects,
                nativeDefragQuarantineBytes,
                nativeStaleHandleDetections,
                nativeDefragReclaimedPages,
                0L
        );
    }
}
