<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>yier.bubu.redis</groupId>
        <artifactId>yierdis-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yierdis-memory</artifactId>
    <packaging>pom</packaging>

    <name>yierdis-memory</name>
    <description>Aggregator and parent for Yierdis memory modules.</description>

    <modules>
        <module>yierdis-memory-api</module>
        <module>yierdis-memory-ffm</module>
        <module>yierdis-memory-testkit</module>
    </modules>
</project>
